In [2]:
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([[5,6],[7,8]])
arr3=np.array([[[1,3,5],[7,9,3]],[[2,4,6],[8,6,2]]])
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

1
2
3


In [3]:
arr4=np.array([1,2,3,4,5],ndmin=5)
arr5=np.array([1,2,3,4,5],ndmin=6)
arr6=np.array([1,2,3,4,5],ndmin=7)
print(arr4.ndim)
print(arr5.ndim)
print(arr6.ndim)


5
6
7


In [4]:
arr=np.array([1,2,3,4,5,6,7])
print(arr[::2])

[1 3 5 7]


In [5]:
arr=np.array([[5,6],[7,8]])
print(arr[0:2,1:4])

[[6]
 [8]]


In [6]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [7]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [8]:
arr=np.array([1,2,3,4],dtype=bool)
print(arr)
print(arr.dtype)
arr1=np.array([1,2,3,4],dtype='f')
print(arr1)
print(arr1.dtype)


[ True  True  True  True]
bool
[1. 2. 3. 4.]
float32


In [9]:
arr3=np.array([1.2,2.3,4.5],dtype='i')
print(arr3)
print(arr3.dtype)
arr4=np.array([1.2,2.3,4.5],dtype=bool)
print(arr4)
print(arr4.dtype)



[1 2 4]
int32
[ True  True  True]
bool


In [10]:
a=np.array([1,2,3,4,5])
b=a.copy()
print(a)
print(b)
c=b.astype('f')
print(c)
print(c.dtype)
d=a.view()
e=d.astype('S')
print(e)
print(e.dtype)



[1 2 3 4 5]
[1 2 3 4 5]
[1. 2. 3. 4. 5.]
float32
[b'1' b'2' b'3' b'4' b'5']
|S11


In [11]:
arr1=np.linspace(12,36,9)
print(arr1)


[12. 15. 18. 21. 24. 27. 30. 33. 36.]


In [12]:
np.sum([[1,2],[3,4]],axis=0)

array([4, 6])

In [13]:
np.sum([[1,2],[3,4]],axis=1)

array([3, 7])

In [14]:
np.sqrt(4)

2.0

In [15]:
np.sqrt([[1,2],[3,4]])

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [16]:
np.std([85,92,78,88,92,96,78,85,90,88])

5.582114294781145

In [17]:
np.mean([85,92,78,88,92,96,78,85,90,88])

87.2

In [18]:
np.median([85,92,78,88,92,96,78,85,90,88])

88.0

In [19]:
import statistics
np.median([85,92,78,88,92,96,78,85,90,88])

88.0

In [20]:
np.std([85,92,78,88,92,96,78,85,90,88])

5.582114294781145

In [21]:
np.mean([85,92,78,88,92,96,78,85,90,88])

87.2

In [22]:
np.var([85,92,78,88,92,96,78,85,90,88])

31.160000000000004

In [23]:
arr=np.array([1,2,3,4],ndmin=5)
print(arr.shape)


(1, 1, 1, 1, 4)


In [24]:
a=np.array([1,2,3,4,5])
print(a.min())
print(a.max())

1
5


In [25]:
b=np.array([1,2,3,4,5,6,9])
c=b.copy()
print(c)
np.sqrt(c)

[1 2 3 4 5 6 9]


array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 3.        ])

In [26]:
arr1=np.linspace(12,36,9)
print(arr1)

[12. 15. 18. 21. 24. 27. 30. 33. 36.]


In [27]:
print(arr1.shape)

(9,)


In [28]:
a=np.array([12,15, 18, 21, 24,27,30, 33, 36],ndmin=4)
print(a.shape)

(1, 1, 1, 9)


In [29]:
arr2=arr1.reshape(3,3)
print(arr2)

[[12. 15. 18.]
 [21. 24. 27.]
 [30. 33. 36.]]


In [1]:
import numpy as np
arr=np.array([1,2,3,4,5])
for x in arr:
    print(x)

1
2
3
4
5


In [9]:
arr1=np.array([[1,2,3],[4,5,6]])
for x in arr1:
    print(x)
    
    for y in x:
        print(y)

[1 2 3]
1
2
3
[4 5 6]
4
5
6


In [8]:
arr2=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in arr2:
    
    for y in x:
        
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [10]:
arr2=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in np.nditer(arr2):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12


In [14]:
arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']): #'S' means string with bytes
    print(x)

b'1'
b'2'
b'3'


In [13]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
    print(x)

1
3
5
7


In [15]:
arr = np.array([1, 2, 3,4,5])
for x,y in np.ndenumerate(arr):
    print(x,y)

(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5


In [16]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for x,y in np.ndenumerate(arr):
    print(x,y)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [17]:
arr = np.array([[[1, 2, 3, 4], [5, 6, 7, 8]],[[9,10,11,12],[13,14,15,16]]])
for x,y in np.ndenumerate(arr):
    print(x,y)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 1, 0) 5
(0, 1, 1) 6
(0, 1, 2) 7
(0, 1, 3) 8
(1, 0, 0) 9
(1, 0, 1) 10
(1, 0, 2) 11
(1, 0, 3) 12
(1, 1, 0) 13
(1, 1, 1) 14
(1, 1, 2) 15
(1, 1, 3) 16


In [18]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [19]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [20]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=0)

print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [21]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [24]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [25]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1, arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


In [26]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])
arr = np.dstack((arr1, arr2))
print(arr)



[[[1 4]
  [2 5]
  [3 6]]]


In [2]:
import numpy as np
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
arr=np.hstack((arr1,arr2))
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [12]:
arr=np.vstack((arr1,arr2))
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [6]:
x=arr.reshape(-1)
print(x)

[ 1  2  3  4  5  6  7  8  9 10]


In [11]:
y=x.reshape(2,5,1)
print(y)

[[[ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]]]


In [18]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
arr=np.vstack((arr1,arr2))
print(arr)
x=arr.reshape(-1)
print(x)



[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[ 1  2  3  4  5  6  7  8  9 10]


In [1]:
import numpy as np
arr1=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
arr=np.array_split(arr1,4)
print(arr)

[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11]), array([12, 13, 14])]


In [3]:
import numpy as np
arr1=np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
arr=np.array_split(arr1,3)
print(arr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [4]:
arr1=np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
arr=np.array_split(arr1,3,axis=1)
print(arr)

[array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11]]), array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12]]), array([], shape=(6, 0), dtype=int32)]


In [6]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.array_split(arr, 3, axis=1) #axis=1 is along rows
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [7]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.hsplit(arr, 3) #hsplit: split along rows same as axis=1
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [8]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.vsplit(arr, 3) #similar to vstack
print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [9]:
arr = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])
newarr = np.dsplit(arr, 3) #similar to dstack
print(newarr)

[array([[[ 1],
        [ 4],
        [ 7]],

       [[10],
        [13],
        [16]]]), array([[[ 2],
        [ 5],
        [ 8]],

       [[11],
        [14],
        [17]]]), array([[[ 3],
        [ 6],
        [ 9]],

       [[12],
        [15],
        [18]]])]


In [16]:
arr1=np.array([1,2,3,4,5,6,4])
x=np.where(arr1 == 4)
print(x)


(array([3, 6], dtype=int64),)


In [17]:
arr1=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
x=np.where(arr1%2==0)
print(x)

(array([ 1,  3,  5,  7,  9, 11, 13], dtype=int64),)


In [18]:
arr1=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
x=np.where(arr1%2==1)
print(x)

(array([ 0,  2,  4,  6,  8, 10, 12], dtype=int64),)


In [19]:
arr1=np.array([1,2,3,4,5,6,7])
x=np.searchsorted(arr1,4)
print(x)

3


In [20]:
arr1=np.array([1,2,3,4,5,6,7])
x=np.searchsorted(arr1,8)
print(x)

7


In [21]:
arr1=np.array([1,2,3,4,5,6,7])
x=np.searchsorted(arr1,8,side='right')
print(x)

7


In [22]:
arr1=np.array([1,2,3,4,5,6,7])
x=np.searchsorted(arr1,2,side='right')
print(x)

2


In [23]:
arr1=np.array([1,2,3,4,5])
x=np.searchsorted(arr1,3,side='right')
print(x)

3


In [24]:
arr = np.array([1, 3, 5, 7])
x = np.searchsorted(arr, [2, 4, 6])
print(x)

[1 2 3]


In [25]:
arr = np.array([2,4,6,8])
x = np.searchsorted(arr, [1,3,5,7])
print(x)

[0 1 2 3]


In [29]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(arr1+arr2)

[5 7 9]


In [30]:
arr1=np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [37]:
arr2=np.array([[0,0,0],[0,0,0],[0,0,0]],ndmin=2)
print(arr2)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [38]:
arr=np.array([1,2,3,4,5])
print(arr[2])

3


In [39]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
print(arr1+arr2)

[5 7 9]


In [40]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.add(arr1,arr2)
print(arr)

[5 7 9]


In [42]:
# 2,3,5,3,7,8,4,3,9
x=np.std([2,3,5,3,7,8,4,3,9])
print(x)
y=np.mean([2,3,5,3,7,8,4,3,9])
print(y)


2.3778816176702997
4.888888888888889


In [46]:
x=np.linspace(1,100,10,dtype='i')
print(x)

[  1  12  23  34  45  56  67  78  89 100]


In [1]:
#Day16
import numpy as np
a=np.zeros([2,2],dtype=int)
print(a)


[[0 0]
 [0 0]]


In [22]:
arr=np.arange(1,10,2,dtype='i')
print(arr)

[1 3 5 7 9]


In [31]:
arr=np.empty([3,3],dtype=int)
print(arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [36]:
arr=np.ones([3,3],dtype=int)
print(arr)
print(arr.itemsize)
print(arr.dtype)


[[1 1 1]
 [1 1 1]
 [1 1 1]]
4
int32


In [39]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
print(arr.flatten())
print(arr.flatten('C')) #row-major order
print(arr.flatten('F'))#column-major order

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
[ 1  4  7 10 13 16  2  5  8 11 14 17  3  6  9 12 15 18]


In [42]:
arr=np.eye(2,dtype='i')
print(arr)
a1=np.eye(3,dtype='f')
print(a1)
a2=np.eye(4,3,dtype='i')
print(a2)

[[1 0]
 [0 1]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0]
 [0 1 0]
 [0 0 1]
 [0 0 0]]


In [50]:
arr=np.random.rand(2,3)
print(arr)
arr1=np.random.randn(2,3)
print(arr1)


[[0.19318658 0.68668099 0.0893807 ]
 [0.78943626 0.72270534 0.73060994]]
[[-0.48216337  0.32383452 -1.62124702]
 [-1.58328958 -1.68889187  1.4117215 ]]


In [52]:
a=np.arange(1,1000)
print(a.max())
print(a.min())

999
1


In [53]:
a=np.array([1,5,9,2,4,8])
print(a.argmax()) #displays index value of the highest number
print(a.argmin()) #displays index value of the lowest number

2
0


In [55]:
arr=np.full((3,4),5)
print(arr)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [57]:
a=np.array([1,5,9,2,4,8])
print(np.exp(a))
print(np.sqrt(a))

[2.71828183e+00 1.48413159e+02 8.10308393e+03 7.38905610e+00
 5.45981500e+01 2.98095799e+03]
[1.         2.23606798 3.         1.41421356 2.         2.82842712]


In [61]:
a=np.array([1,2,3,4,5])
b=np.empty_like(a)
print(b)
c=np.copy(a)
print(c)

[1 2 3 4 5]
[1 2 3 4 5]


In [69]:
a=np.array([101,2,3,4,100])
b=np.array([22,44,11,77,99])
print(a)
print(b)
print(np.greater(a,b))
print(np.greater_equal(a,b))
print(np.less(a,b))
print(np.less_equal(a,b))

[101   2   3   4 100]
[22 44 11 77 99]
[ True False False False  True]
[ True False False False  True]
[False  True  True  True False]
[False  True  True  True False]


In [70]:
if np.array_equal(a,b):
    print("equal")
else:
    print("False")

False


In [1]:
amt=int(input("Enter the Budget:"))
a=amt
while True:
    
    print("1.Add\n 2.Exit")
    ch=int(input("Enter your choice:"))
    if ch==1 and a>0:
        item=input("Enter the item name:")
        price=int(input("Enter the price:"))
        a=a-price
        print(f"The amount left is {a}")
    elif a==0:
        print("The amount is insufficient to buy this item.")
        break
    if ch==2:
        break

copy_items={"item_name":[],"item_price":[]}


    

    
    

    

Enter the Budget:100
1.Add
 2.Exit
Enter your choice:1
Enter the item name:rrr
Enter the price:50
The amount left is 50
1.Add
 2.Exit
Enter your choice:1
Enter the item name:eee
Enter the price:50
The amount left is 0
1.Add
 2.Exit
Enter your choice:1
The amount is insufficient to buy this item.
